### ISSUE TITLE
Trouble installing plugin

### ISSUE THREAD

**Issue by cdosborn** [cHoco/noTitleBar-Terminal#1]
I cannot install the plugin.

I ran `make/make install` just fine.

I downloaded `EasySIMBL`, selected "Use SIMBL". and dropped the bundle into the list. 

I tried to reopen `Terminal.app` and the title bar is still there.

Is there something I'm missing. I have never used simbl before. I'm running El Capitan.

**Comment by choco** [comment]
Hi,

unfortunately EasySIMBL doesn't work due to the System Integrity Protection system introduced in El Capitan, you'll have to use legacy SIMBL.
Here's a guide by the EasySIMBL author on how to get it working: https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426 but first uninstall EasySIMBL (just delete the app)
After performing the steps above make sure there's a file `noTitleBar-Terminal.bundle` in the  `~/Library/Application Support/SIMBL/Plugins` directory (if you performed the `make install` command a copy should already be installed there)

**Comment by cdosborn** [comment]
Thanks for the help.
