### ISSUE TITLE
How to hide the bar on other app?

### ISSUE THREAD

**Issue by dortamiguel** [cHoco/noTitleBar-Terminal#7]
I want to hide the title bar of sublime text 3 and it has this bundle identifier

com.sublimetext.3

I changed it on the BundleIdentifier in the info.plist but it's not doing anything.

**Comment by choco** [comment]
I should probably add a note that this project is dead (and has been for almost a year) since iTerm2 renders text just like Terminal app now.
As per the issue above, the code is written to only work on Terminal.app, it looks for the specific NSWindow subclass used by it and also uses a method provided by the app that let's me iterate over the available windows. In other words it won't work with other apps, just by changing the bundle identifier.
You can also find more context here: https://github.com/choco/noTitleBar-Terminal/issues/3
